// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/file_stream.proto

package filestream

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileStreamService_DownloadFile_FullMethodName = "/file_streaming.FileStreamService/DownloadFile"
)

// FileStreamServiceClient is the client API for FileStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileStreamServiceClient interface {
	DownloadFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Filechunk], error)
}

type fileStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileStreamServiceClient(cc grpc.ClientConnInterface) FileStreamServiceClient {
	return &fileStreamServiceClient{cc}
}

func (c *fileStreamServiceClient) DownloadFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Filechunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileStreamService_ServiceDesc.Streams[0], FileStreamService_DownloadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileRequest, Filechunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileStreamService_DownloadFileClient = grpc.ServerStreamingClient[Filechunk]

// FileStreamServiceServer is the server API for FileStreamService service.
// All implementations must embed UnimplementedFileStreamServiceServer
// for forward compatibility.
type FileStreamServiceServer interface {
	DownloadFile(*FileRequest, grpc.ServerStreamingServer[Filechunk]) error
	mustEmbedUnimplementedFileStreamServiceServer()
}

// UnimplementedFileStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileStreamServiceServer struct{}

func (UnimplementedFileStreamServiceServer) DownloadFile(*FileRequest, grpc.ServerStreamingServer[Filechunk]) error {
	return status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedFileStreamServiceServer) mustEmbedUnimplementedFileStreamServiceServer() {}
func (UnimplementedFileStreamServiceServer) testEmbeddedByValue()                           {}

// UnsafeFileStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileStreamServiceServer will
// result in compilation errors.
type UnsafeFileStreamServiceServer interface {
	mustEmbedUnimplementedFileStreamServiceServer()
}

func RegisterFileStreamServiceServer(s grpc.ServiceRegistrar, srv FileStreamServiceServer) {
	// If the following call pancis, it indicates UnimplementedFileStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileStreamService_ServiceDesc, srv)
}

func _FileStreamService_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileStreamServiceServer).DownloadFile(m, &grpc.GenericServerStream[FileRequest, Filechunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileStreamService_DownloadFileServer = grpc.ServerStreamingServer[Filechunk]

// FileStreamService_ServiceDesc is the grpc.ServiceDesc for FileStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "file_streaming.FileStreamService",
	HandlerType: (*FileStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadFile",
			Handler:       _FileStreamService_DownloadFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/file_stream.proto",
}
